name: Docker CI/CD

on:
  # push:
  #   branches: [ main ]
  #   paths:
  #     - src/**
  pull_request:
    branches: [ main ]
    paths:
      - src/**

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with flake8
      run: |
        flake8 $(git ls-files '*.py')   

  build:
    name: build and push Docker image
    runs-on: ubuntu-latest
    needs: lint 
    steps:
      - uses: actions/checkout@v4
          
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops02:latest

  aws:
    name: Deploy image to aws
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: copy docker compose via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USER }}
        port: 22 # ${{ secrets.PORT }}
        key: ${{ secrets.AWS_KEY }}
        source: "docker-compose.yml"
        target: /home/admin
    - name: script deploy docker services
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USER}}
        key: ${{ secrets.AWS_KEY }}
        port: 22  # ${{ secrets.PORT }}
        script: |
            sleep 60
            docker compose down --rmi all
            docker compose up -d




# https://github.com/docker/login-action
# https://github.com/docker/build-push-action
# https://github.com/appleboy/ssh-actionname: Docker CI/CD



  